.TH CALIBRATE 8 "28 April 1998" Linux "Linux Programmer's Manual"
.SH NAME
calibrate \- URONode user information lookup program
.SH SYNOPSIS
.B calibrate
.SH DESCRIPTION
.LP
.B calibrate \-t ## interface
tool by F1OAT ported for compile and use with URONode to calibrate radios.
.SH OPTIONS
.TP 10
.BI \-t
Time in ms to engage the calibration of an interface (often mislabeled port).
.TP 10
.BI interface
This is the interface you wish to calibrate. 
.SH FILES
.LP
.TP 5
.B /etc/ax25/axports
List of ax25 interfaces.
.SH "SEE ALSO"
.BR uronode (8)
.SH AUTHOR
Brian Rogers N1URO <n1uro@n1uro.com>
.br
Stefano Noferi IZ5AWZ <iz5awz@radio-ge.cnuce.cnr.it>
.br
Tomi Manninen OH2BNS <tpmannin@cc.hut.fi>
